//-----------------------------------------------------------------------------
// Demo API
//-----------------------------------------------------------------------------

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DemoSpecApplyConfiguration represents an declarative configuration of the DemoSpec type for use
// with apply.
type DemoSpecApplyConfiguration struct {
	Message *string `json:"message,omitempty"`
}

// DemoSpecApplyConfiguration constructs an declarative configuration of the DemoSpec type for use with
// apply.
func DemoSpec() *DemoSpecApplyConfiguration {
	return &DemoSpecApplyConfiguration{}
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *DemoSpecApplyConfiguration) WithMessage(value string) *DemoSpecApplyConfiguration {
	b.Message = &value
	return b
}
