//-----------------------------------------------------------------------------
// Demo API
//-----------------------------------------------------------------------------

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package applyconfigurations

import (
	v1 "github.com/laforge-tech/k8stypes/pkg/api/demo/v1"
	demov1 "github.com/laforge-tech/k8stypes/pkg/applyconfigurations/demo/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

// ForKind returns an apply configuration type for the given GroupVersionKind, or nil if no
// apply configuration type exists for the given GroupVersionKind.
func ForKind(kind schema.GroupVersionKind) interface{} {
	switch kind {
	// Group=demo, Version=v1
	case v1.SchemeGroupVersion.WithKind("Demo"):
		return &demov1.DemoApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DemoSpec"):
		return &demov1.DemoSpecApplyConfiguration{}
	case v1.SchemeGroupVersion.WithKind("DemoStatus"):
		return &demov1.DemoStatusApplyConfiguration{}

	}
	return nil
}
