//-----------------------------------------------------------------------------
// Demo API
//-----------------------------------------------------------------------------

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/laforge-tech/k8stypes/pkg/client/typed/demo/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeDemoV1 struct {
	*testing.Fake
}

func (c *FakeDemoV1) Demos(namespace string) v1.DemoInterface {
	return &FakeDemos{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeDemoV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
